name: release
on:
  push:
    tags:
      - '*'
jobs:

  release-macos:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: '25.0.1'
          java-package: 'jdk+fx'
          cache: maven
      - run: mvn -pl core,desktop clean package
      - uses: softprops/action-gh-release@v2
        with:
          files: desktop/target/distribution/*

  release-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: '25.0.1'
          java-package: 'jdk+fx'
          cache: maven
      - run: sudo apt install desktop-file-utils
      - run: mvn -pl core,desktop clean package
      - uses: softprops/action-gh-release@v2
        with:
          files: desktop/target/distribution/*

  release-fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          set-safe-directory: ${{github.workspace}}
      - uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: '25.0.1'
          java-package: 'jdk+fx'
          cache: maven
      - run: sudo dnf install -y maven rpm-build
      - run: mvn -pl core,desktop clean package
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            desktop/target/distribution/*.rpm
            desktop/target/distribution/*.rpm.sha256

  release-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: '25.0.1'
          java-package: 'jdk+fx'
          cache: maven
      - run: mvn -pl core,desktop clean package
      - uses: softprops/action-gh-release@v2
        with:
          files: desktop/target/distribution/*